### ISSUE TITLE
"TypeError: missing a required argument" starting with v5.0.5

### ISSUE THREAD

**Issue by ProgVal** [micheles/decorator#109]
Hi,

I started getting `TypeError: missing a required argument: 'self'` in some code I run since I upgraded to decorator v5.0.5.

Here is some code to reproduce it, using pytest:

```
import functools
from collections import defaultdict
from inspect import getcallargs
from flask import Flask, Request, Response, abort, request
from decorator import decorator
import msgpack


class Formatter:
    format = None
    mimetypes = []

    def __init__(self, request_mimetype = None) -> None:
        if request_mimetype is None or request_mimetype not in self.mimetypes:
            try:
                self.response_mimetype = self.mimetypes[0]
            except IndexError:
                raise NotImplementedError(
                    "%s.mimetypes should be a non-empty list" % self.__class__.__name__
                )
        else:
            self.response_mimetype = request_mimetype

    def __call__(self, obj) -> Response:
        return self._make_response(
            self.render(obj), content_type=self.response_mimetype
        )


class MsgpackFormatter(Formatter):
    format = "msgpack"
    mimetypes = ["application/x-msgpack"]

    def render(self, obj):
        return msgpack_dumps(obj, extra_encoders=self.extra_encoders)


class Negotiator:
    def __init__(self, func) -> None:
        self.func = func

    def __call__(self, *args, **kwargs) -> Response:
        return msgpack.dumps(self.func(*args, **kwargs))

def negotiate(formatter_cls, *args, **kwargs):
    negotiator_cls = Negotiator
    def _negotiate(f, *args, **kwargs):
        return f.negotiator(*args, **kwargs)

    def decorate(f):
        if not hasattr(f, "negotiator"):
            f.negotiator = negotiator_cls(f)

        return decorator(_negotiate, f)

    return decorate

class Backend:
    def foo(self, data):
        pass

class MyRPCServerApp2(Flask):

    def __init__(self, *args, backend_class=None, backend_factory=None, **kwargs):
        super().__init__(*args, **kwargs)
        if backend_class is None and backend_factory is not None:
            raise ValueError(
                "backend_factory should only be provided if backend_class is"
            )

        self.backend_class = backend_class
        if backend_class is not None:
            backend_factory = backend_factory or backend_class
            for (meth_name, meth) in backend_class.__dict__.items():
                if meth_name == "foo":
                    self.__add_endpoint(meth_name, meth, backend_factory)

    def __add_endpoint(self, meth_name, meth, backend_factory):
        from flask import request

        @self.route("/foo", methods=["POST"])
        @negotiate(MsgpackFormatter)
        @functools.wraps(meth)  # Copy signature and doc
        def _f():
            return "all good"

def test_flask():
    app = MyRPCServerApp2("testapp", backend_class=Backend)
    with app.test_client() as client:
        res = client.post(
            "/foo",
        )

        assert res.status_code == 200
        assert res.data == b"\xa8all good"
```

(forgive the mess, I'm a little lost myself)

With decorator up to v5.0.4, it passes. With decorator v5.0.5, it errors with:

```
ERROR    testapp:app.py:1892 Exception on /foo [POST]
Traceback (most recent call last):
  File "/home/dev/.local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dev/.local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dev/.local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dev/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dev/.local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dev/.local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dev/.local/lib/python3.7/site-packages/decorator.py", line 231, in fun
    args, kw = fix(args, kw, sig)
  File "/home/dev/.local/lib/python3.7/site-packages/decorator.py", line 203, in fix
    ba = sig.bind(*args, **kwargs)
  File "/usr/lib/python3.7/inspect.py", line 3015, in bind
    return args[0]._bind(args[1:], kwargs)
  File "/usr/lib/python3.7/inspect.py", line 2930, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'self'
```

I hope you can make some sense of it. I can give an other try at producing a minimal example otherwise.

Thanks!

**Comment by micheles** [comment]
Probably you need to mimic functools.wraps. There is the flag kwsyntax for that, see https://github.com/micheles/decorator/blob/master/docs/documentation.md#mimicking-the-behavior-of-functoolswrap

**Comment by ProgVal** [comment]
@micheles Thanks. I ended up rewriting this code with `functools.wraps`, I don't think the code I pasted needed to use `decorator`, but I'll keep it in mind if the rewrite causes issues.
