### ISSUE TITLE
Failing to build hue

### ISSUE THREAD

**Issue by davidrabinowitz** [micheles/decorator#110]
I'm trying to build Hue version 4.5.0, and it fails due to issue with decorator 5.0.5:
```
Traceback (most recent call last):
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/bin/easy_install", line 11, in <module>
    sys.exit(main())
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2321, in main
    **kw
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 424, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 713, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 758, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 685, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 711, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 896, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1164, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1150, in run_setup
    run_setup(setup_script, args)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/bigtop/bigtop/output/hue/hue-4.5.0/build/env/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-hwpMU7/decorator-5.0.5/setup.py", line 4, in <module>
  File "<string>", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax
```
Can you please have a look?

**Comment by micheles** [comment]
Decorator 5 removed support for Python 2.7. Use version 4 instead.
