### ISSUE TITLE
4.0.1 No such file or directory: 'docs/README.rst'

### ISSUE THREAD

**Issue by barneyjackson** [micheles/decorator#12]
Upgrading to 4.0.1 (latest as of this moment) gives the following error:
```
$ pip install decorator==4.0.1
Downloading/unpacking decorator==4.0.1
  Running setup.py egg_info for package decorator
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "XXX/build/decorator/setup.py", line 12, in <module>
        long_description=open('docs/README.rst').read(),
    IOError: [Errno 2] No such file or directory: 'docs/README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "XXX/build/decorator/setup.py", line 12, in <module>

    long_description=open('docs/README.rst').read(),

IOError: [Errno 2] No such file or directory: 'docs/README.rst'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in XXX/build/decorator
Storing complete log in /home/ubuntu/.pip/pip.log
```

I see the fix in https://github.com/micheles/decorator/commit/18dd1e5efaca2f79688ed78e9ddabdfb647eea9e, but it doesn't seem to have done the job.

4.0.0 works as expected.

**Comment by micheles** [comment]
This should be fixed in 4.0.2
