### ISSUE TITLE
new release breaks IPython

### ISSUE THREAD

**Issue by spapini** [micheles/decorator#47]
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/local/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 120, in <module>
    class Application(SingletonConfigurable):
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 291, in Application
    def initialize(self, argv=None):
TypeError: catch_config_error() takes exactly 2 arguments (1 given)

catch_config_error is a decorator decorated with this package

**Comment by micheles** [comment]
The issue should be fixed in master. Can you try if it works for you?

**Comment by kekssw** [comment]
Works from master for me.

**Comment by micheles** [comment]
Ok, I have released version 4.2.1 now. Sorry for the inconvenience.

**Comment by spapini** [comment]
Thank you!
